---
- name: Upgrade distribution
  apt: update_cache=yes upgrade=yes cache_valid_time=1800

- name: Build tools
  apt: pkg=build-essential

- name: Install base packages
  apt: pkg={{ item }} state=latest
  with_items:
    - vim
    - wget
    - curl
    - screen
    - htop
    - rsync
